Capstone project
francksefu/Capstone-project pull request #1
Opened 2023-02-09 19:14 UTC by francksefu

Add logo, content, and font family in All HTML files
Add the part Featured Speakers dynamically by using JavaScript
Make the whole HTML file responsive

2023-02-09 22:08 UTC, mwanawabangona requested changes
Hi @francksefu ,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 22:08 UTC, mwanawabangona commented on README.md
> +
- [ ] `required`
- [ ] I suggest that here you add the license and remove the acknowledgments 🥂

2023-02-09 22:08 UTC, mwanawabangona commented on README.md
> +> I wanna give thank to Microverse
- [ ] `required`
- [ ] Here I suggest you can even add the `Creative Commons` and `CindyShine` for acknowledgment as the requirements say.

2023-02-09 22:08 UTC, mwanawabangona commented on index.html
> +
- [ ] `required`
- [ ] Amazing job so far! 👏 
- [ ] however, there few things you need to address
- [ ] The welcome headers and need to be moved under the logo.
- [ ] Also please try to make the `Oen house bicc` bigger like the template.
- [ ] Plese see the template below

`your template`
![image](https://user-images.githubusercontent.com/66230306/217948541-2d7d6dad-8a65-4cdc-89c2-80802aa985d4.png)


`original design`
![image](https://user-images.githubusercontent.com/66230306/217947880-52036088-4bb2-4616-9e43-ce2c1d097063.png)

2023-02-09 22:08 UTC, mwanawabangona commented on index.html
> +                  <span class="material-icons text-white hauteur bg-transparent fs-1 col-2">
- [ ] `required`
- [ ] Please the original background just the origin template
- [ ] please see screenshots below for further verification.

`your template`
![image](https://user-images.githubusercontent.com/66230306/217949822-146f0797-aaaf-40ed-90cb-cc1c4fca7052.png)

`original template`
![image](https://user-images.githubusercontent.com/66230306/217949963-f4997495-458d-43b5-989e-f0a2848c0244.png)

2023-02-10 22:23 UTC, vickymarz approved these changes
Hi @francksefu, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Good UI design ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 22:25 UTC, merged